[package]
name = "lang2"
version = "0.1.0"
authors = ["masuke5 <s.zerogoichi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pretty_assertions = "0.6.1"
clap = "2"
