[package]
name = "lang2"
version = "0.1.0"
authors = ["masuke5 <s.zerogoichi@gmail.com>"]
edition = "2018"

[features]
vmdebug = []

[dependencies]
pretty_assertions = "0.6.1"
clap = "2"
lazy_static = "1.4"
libc = "0.2"
rustc-hash = "1.0"
thiserror = "1.0"
